# Netlify Configuration File

# Redirect old domain
[[redirects]]
  from = "https://cryptowalletsx.netlify.app/*"
  to = "https://cryptowalletsx.com/:splat"
  status = 301
  force = true


# Netlify settings
[build]
  publish = ".next"
  command = "npm run build"

# Environment variables
[context.production.environment]
  # Set ThirdWeb client IDs
  NEXT_PUBLIC_THIRDWEB_CLIENT_ID_1 = "from_netlify_env"
  VITE_THIRDWEB_CLIENT_ID_1 = "from_netlify_env"

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 