import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Fogo Chain Stats Checker | FogoChain Wallet Rank & Activity Analyzer',
  description: 'Comprehensive Fogo Chain stats checker and wallet analyzer. Check FogoChain wallet rank, activity, transaction history, staking rewards, and on-chain analytics. Free Fogo stats tool for crypto portfolio tracking.',
  keywords: [
    'fogo chain stats checker',
    'fogochain stats checker', 
    'fogo stats checker',
    'fogochain rank checker',
    'fogo stats',
    'fogochain wallet rank',
    'fogochain activity checker',
    'fogo wallet analyzer',
    'fogochain transaction history',
    'fogo chain analytics',
    'fogochain portfolio tracker',
    'fogo blockchain explorer',
    'fogochain validator stats',
    'fogo chain metrics',
    'fogochain wallet tracker',
    'fogo on-chain analytics',
    'fogochain staking rewards',
    'fogo wallet activity',
    'fogochain transaction analyzer',
    'fogo chain portfolio'
  ],
  authors: [{ name: 'CryptoWalletsX' }],
  creator: 'CryptoWalletsX',
  publisher: 'CryptoWalletsX',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cryptowalletsx.com'),
  alternates: {
    canonical: '/fogo-stats-checker',
  },
  openGraph: {
    title: 'Fogo Chain Stats Checker | FogoChain Wallet Rank & Activity Analyzer',
    description: 'Comprehensive Fogo Chain stats checker and wallet analyzer. Check FogoChain wallet rank, activity, transaction history, staking rewards, and on-chain analytics.',
    url: '/fogo-stats-checker',
    siteName: 'CryptoWalletsX',
    images: [
      {
        url: '/og-fogo-stats-checker.jpg',
        width: 1200,
        height: 630,
        alt: 'Fogo Chain Stats Checker - Wallet Analytics Tool',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Fogo Chain Stats Checker | FogoChain Wallet Analytics',
    description: 'Check your FogoChain wallet rank, activity, and transaction history with our comprehensive stats checker tool.',
    images: ['/og-fogo-stats-checker.jpg'],
    creator: '@cryptowalletsx',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
    yahoo: 'your-yahoo-verification-code',
  },
  category: 'technology',
  classification: 'Cryptocurrency Tools',
  other: {
    'application-name': 'CryptoWalletsX Fogo Stats Checker',
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
    'apple-mobile-web-app-title': 'Fogo Stats Checker',
    'msapplication-TileColor': '#f97316',
    'theme-color': '#f97316',
  },
};
