import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'LayerZero Stats Checker | LayerZero Wallet Rank & Activity Analyzer',
  description: 'Comprehensive LayerZero stats checker and wallet analyzer. Check LayerZero wallet rank, activity, transaction history, bridge analytics, and omnichain metrics. Free LayerZero stats tool for cross-chain portfolio tracking.',
  keywords: [
    'layerzero stats checker',
    'layerzero wallet analyzer', 
    'layerzero rank checker',
    'layerzero stats',
    'layerzero wallet rank',
    'layerzero activity checker',
    'layerzero bridge analyzer',
    'layerzero transaction history',
    'layerzero analytics',
    'layerzero portfolio tracker',
    'layerzero blockchain explorer',
    'layerzero omnichain stats',
    'layerzero wallet tracker',
    'layerzero on-chain analytics',
    'layerzero bridge stats',
    'layerzero wallet activity',
    'layerzero transaction analyzer',
    'layerzero cross-chain portfolio',
    'layerzero network activity',
    'layerzero protocol stats',
    'layerzero omnichain checker',
    'lz stats checker'
  ],
  authors: [{ name: 'CryptoWalletsX' }],
  creator: 'CryptoWalletsX',
  publisher: 'CryptoWalletsX',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cryptowalletsx.com'),
  alternates: {
    canonical: '/layerzero-stats',
  },
  openGraph: {
    title: 'LayerZero Stats Checker | LayerZero Wallet Rank & Activity Analyzer',
    description: 'Comprehensive LayerZero stats checker and wallet analyzer. Check LayerZero wallet rank, activity, transaction history, bridge analytics, and omnichain metrics.',
    url: '/layerzero-stats',
    siteName: 'CryptoWalletsX',
    images: [
      {
        url: '/og-layerzero-stats-checker.jpg',
        width: 1200,
        height: 630,
        alt: 'LayerZero Stats Checker - Wallet Analytics Tool',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'LayerZero Stats Checker | LayerZero Wallet Analytics',
    description: 'Check your LayerZero wallet rank, activity, and transaction history with our comprehensive stats checker tool.',
    images: ['/og-layerzero-stats-checker.jpg'],
    creator: '@cryptowalletsx',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
    yahoo: 'your-yahoo-verification-code',
  },
  category: 'technology',
  classification: 'Cryptocurrency Tools',
  other: {
    'application-name': 'CryptoWalletsX LayerZero Stats Checker',
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
    'apple-mobile-web-app-title': 'LayerZero Stats Checker',
    'msapplication-TileColor': '#1e40af',
    'theme-color': '#1e40af',
  },
};
