import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Relay Stats Checker | Relay Network Wallet Rank & Activity Analyzer',
  description: 'Comprehensive Relay Network stats checker and wallet analyzer. Check Relay wallet rank, activity, transaction history, bridge analytics, and on-chain metrics. Free Relay stats tool for cross-chain portfolio tracking.',
  keywords: [
    'relay stats checker',
    'relay network stats checker', 
    'relay wallet analyzer',
    'relay rank checker',
    'relay stats',
    'relay network wallet rank',
    'relay activity checker',
    'relay bridge analyzer',
    'relay transaction history',
    'relay chain analytics',
    'relay portfolio tracker',
    'relay blockchain explorer',
    'relay network metrics',
    'relay wallet tracker',
    'relay on-chain analytics',
    'relay bridge stats',
    'relay wallet activity',
    'relay transaction analyzer',
    'relay chain portfolio',
    'relay network activity'
  ],
  authors: [{ name: 'CryptoWalletsX' }],
  creator: 'CryptoWalletsX',
  publisher: 'CryptoWalletsX',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cryptowalletsx.com'),
  alternates: {
    canonical: '/relay-stats-checker',
  },
  openGraph: {
    title: 'Relay Stats Checker | Relay Network Wallet Rank & Activity Analyzer',
    description: 'Comprehensive Relay Network stats checker and wallet analyzer. Check Relay wallet rank, activity, transaction history, bridge analytics, and on-chain metrics.',
    url: '/relay-stats-checker',
    siteName: 'CryptoWalletsX',
    images: [
      {
        url: '/og-relay-stats-checker.jpg',
        width: 1200,
        height: 630,
        alt: 'Relay Stats Checker - Wallet Analytics Tool',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Relay Stats Checker | Relay Network Wallet Analytics',
    description: 'Check your Relay Network wallet rank, activity, and transaction history with our comprehensive stats checker tool.',
    images: ['/og-relay-stats-checker.jpg'],
    creator: '@cryptowalletsx',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
    yahoo: 'your-yahoo-verification-code',
  },
  category: 'technology',
  classification: 'Cryptocurrency Tools',
  other: {
    'application-name': 'CryptoWalletsX Relay Stats Checker',
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
    'apple-mobile-web-app-title': 'Relay Stats Checker',
    'msapplication-TileColor': '#3b82f6',
    'theme-color': '#3b82f6',
  },
};
