import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Pharos Stats Checker | Pharos Testnet Wallet Rank & Activity Analyzer',
  description: 'Comprehensive Pharos Testnet stats checker and wallet analyzer. Check Pharos wallet rank, activity, transaction history, testnet analytics, and on-chain metrics. Free Pharos stats tool for testnet portfolio tracking.',
  keywords: [
    'pharos stats checker',
    'pharos testnet stats checker', 
    'pharos wallet analyzer',
    'pharos rank checker',
    'pharos stats',
    'pharos testnet wallet rank',
    'pharos activity checker',
    'pharos testnet analyzer',
    'pharos transaction history',
    'pharos testnet analytics',
    'pharos portfolio tracker',
    'pharos blockchain explorer',
    'pharos testnet metrics',
    'pharos wallet tracker',
    'pharos on-chain analytics',
    'pharos testnet stats',
    'pharos wallet activity',
    'pharos transaction analyzer',
    'pharos testnet portfolio',
    'pharos network activity',
    'pharos validator stats',
    'pharos testnet checker'
  ],
  authors: [{ name: 'CryptoWalletsX' }],
  creator: 'CryptoWalletsX',
  publisher: 'CryptoWalletsX',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cryptowalletsx.com'),
  alternates: {
    canonical: '/pharos-stats-checker',
  },
  openGraph: {
    title: 'Pharos Stats Checker | Pharos Testnet Wallet Rank & Activity Analyzer',
    description: 'Comprehensive Pharos Testnet stats checker and wallet analyzer. Check Pharos wallet rank, activity, transaction history, testnet analytics, and on-chain metrics.',
    url: '/pharos-stats-checker',
    siteName: 'CryptoWalletsX',
    images: [
      {
        url: '/og-pharos-stats-checker.jpg',
        width: 1200,
        height: 630,
        alt: 'Pharos Stats Checker - Wallet Analytics Tool',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Pharos Stats Checker | Pharos Testnet Wallet Analytics',
    description: 'Check your Pharos Testnet wallet rank, activity, and transaction history with our comprehensive stats checker tool.',
    images: ['/og-pharos-stats-checker.jpg'],
    creator: '@cryptowalletsx',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
    yahoo: 'your-yahoo-verification-code',
  },
  category: 'technology',
  classification: 'Cryptocurrency Tools',
  other: {
    'application-name': 'CryptoWalletsX Pharos Stats Checker',
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
    'apple-mobile-web-app-title': 'Pharos Stats Checker',
    'msapplication-TileColor': '#06b6d4',
    'theme-color': '#06b6d4',
  },
};
