import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Linea Stats Checker | Linea Network Wallet Rank & Activity Analyzer',
  description: 'Comprehensive Linea Network stats checker and wallet analyzer. Check Linea wallet rank, activity, transaction history, bridge analytics, and L2 metrics. Free Linea stats tool for Ethereum L2 portfolio tracking.',
  keywords: [
    'linea stats checker',
    'linea network stats checker', 
    'linea wallet analyzer',
    'linea rank checker',
    'linea stats',
    'linea network wallet rank',
    'linea activity checker',
    'linea bridge analyzer',
    'linea transaction history',
    'linea network analytics',
    'linea portfolio tracker',
    'linea blockchain explorer',
    'linea l2 stats',
    'linea wallet tracker',
    'linea on-chain analytics',
    'linea bridge stats',
    'linea wallet activity',
    'linea transaction analyzer',
    'linea network portfolio',
    'linea ethereum l2',
    'linea consensys stats',
    'linea metamask checker'
  ],
  authors: [{ name: 'CryptoWalletsX' }],
  creator: 'CryptoWalletsX',
  publisher: 'CryptoWalletsX',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cryptowalletsx.com'),
  alternates: {
    canonical: '/linea',
  },
  openGraph: {
    title: 'Linea Stats Checker | Linea Network Wallet Rank & Activity Analyzer',
    description: 'Comprehensive Linea Network stats checker and wallet analyzer. Check Linea wallet rank, activity, transaction history, bridge analytics, and L2 metrics.',
    url: '/linea',
    siteName: 'CryptoWalletsX',
    images: [
      {
        url: '/og-linea-stats-checker.jpg',
        width: 1200,
        height: 630,
        alt: 'Linea Stats Checker - Wallet Analytics Tool',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Linea Stats Checker | Linea Network Wallet Analytics',
    description: 'Check your Linea Network wallet rank, activity, and transaction history with our comprehensive stats checker tool.',
    images: ['/og-linea-stats-checker.jpg'],
    creator: '@cryptowalletsx',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
    yahoo: 'your-yahoo-verification-code',
  },
  category: 'technology',
  classification: 'Cryptocurrency Tools',
  other: {
    'application-name': 'CryptoWalletsX Linea Stats Checker',
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
    'apple-mobile-web-app-title': 'Linea Stats Checker',
    'msapplication-TileColor': '#000000',
    'theme-color': '#000000',
  },
};
