import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Jumper Stats Checker | Jumper Exchange Wallet Rank & Activity Analyzer',
  description: 'Comprehensive Jumper Exchange stats checker and wallet analyzer. Check Jumper wallet rank, activity, transaction history, bridge analytics, and cross-chain metrics. Free Jumper stats tool for DeFi portfolio tracking.',
  keywords: [
    'jumper stats checker',
    'jumper exchange stats checker', 
    'jumper wallet analyzer',
    'jumper rank checker',
    'jumper stats',
    'jumper exchange wallet rank',
    'jumper activity checker',
    'jumper bridge analyzer',
    'jumper transaction history',
    'jumper exchange analytics',
    'jumper portfolio tracker',
    'jumper defi explorer',
    'jumper exchange metrics',
    'jumper wallet tracker',
    'jumper on-chain analytics',
    'jumper bridge stats',
    'jumper wallet activity',
    'jumper transaction analyzer',
    'jumper exchange portfolio',
    'jumper cross-chain activity',
    'li.quest stats',
    'liquest analyzer'
  ],
  authors: [{ name: 'CryptoWalletsX' }],
  creator: 'CryptoWalletsX',
  publisher: 'CryptoWalletsX',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cryptowalletsx.com'),
  alternates: {
    canonical: '/jumper-stats-checker',
  },
  openGraph: {
    title: 'Jumper Stats Checker | Jumper Exchange Wallet Rank & Activity Analyzer',
    description: 'Comprehensive Jumper Exchange stats checker and wallet analyzer. Check Jumper wallet rank, activity, transaction history, bridge analytics, and cross-chain metrics.',
    url: '/jumper-stats-checker',
    siteName: 'CryptoWalletsX',
    images: [
      {
        url: '/og-jumper-stats-checker.jpg',
        width: 1200,
        height: 630,
        alt: 'Jumper Stats Checker - Wallet Analytics Tool',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Jumper Stats Checker | Jumper Exchange Wallet Analytics',
    description: 'Check your Jumper Exchange wallet rank, activity, and transaction history with our comprehensive stats checker tool.',
    images: ['/og-jumper-stats-checker.jpg'],
    creator: '@cryptowalletsx',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
    yahoo: 'your-yahoo-verification-code',
  },
  category: 'technology',
  classification: 'Cryptocurrency Tools',
  other: {
    'application-name': 'CryptoWalletsX Jumper Stats Checker',
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
    'apple-mobile-web-app-title': 'Jumper Stats Checker',
    'msapplication-TileColor': '#8b5cf6',
    'theme-color': '#8b5cf6',
  },
};
